### ISSUE TITLE
I ssearch a user named 505 but show out to be a wrong one

### ISSUE THREAD

**Issue by michaelbIgbao** [Postcatlab/postcat#233]
### Describe the bug

Wrong search result
I search user 505 but turned out to be other user i dont know
![](https://user-images.githubusercontent.com/15225835/217715554-4023889a-fe15-41b1-a9b9-73b001fb14a6.png)

### Environment

Postcat v0.1.0

**Comment by Changeeer** [comment]
感谢反馈，已经排查修复
