### ISSUE TITLE
opendlp插件无法使用

### ISSUE THREAD

**Issue by zjx672271706** [Postcatlab/postcat#239]
### Describe the bug

opendlp配置服务器后仍然无法使用
![图片](https://user-images.githubusercontent.com/33922420/219573741-7ca92adb-dbab-4dc2-bdb0-b3c92b441d10.png)
![图片](https://user-images.githubusercontent.com/33922420/219573832-603f2ea8-2eac-4013-9436-d2412dbe84ca.png)

### Environment

Postcat 0.1.0 beta

**Comment by scarqin** [comment]
@zjx672271706 感谢，本周会被修复。
PS 我们客户端已经升级到了 0.2.1，欢迎更新
