### ISSUE TITLE
chrome curl cmd to postcat

### ISSUE THREAD

**Issue by liujunandzhou** [Postcatlab/postcat#244]
### Describe the feature

将curl的完整命令，转化为postcat的请求

### Environment

- 版本: 0.3.0
- Engine: webkit
- EngineVs: 537.36
- Supporter: chrome
- SupporterVs: 103.0.0.0
- System: windows
- SystemVs: 10
- 平台: Web

**Comment by scarqin** [comment]
@liujunandzhou Curl 数据用于复现测试吗？还是保存为 API 文档。

**Comment by mazhiyuam** [comment]
+1 
希望能把curl转成请求用于API测试调试

**Comment by scarqin** [comment]
@liujunandzhou @mazhiyuam 近期会考虑支持

**Comment by keyjane** [comment]
还没有实现么

**Comment by scarqin** [comment]
@keyjane 在做了在做了

**Comment by illbnm** [comment]
这个功能挺常用的

**Comment by scarqin** [comment]
@liujunandzhou @keyjane @liujunandzhou v0.5.0 已经支持啦！
将 Curl 文本粘贴到这里：
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/15225835/229663973-7439b321-9286-4e4d-9f0a-228ffda805b8.png">

后续会考虑通过插件支持～
