### ISSUE TITLE
form-data提交时，参数值最大值不够输入

### ISSUE THREAD

**Issue by fujikang** [Postcatlab/postcat#246]
### Describe the bug

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/35111141/221745238-bb089e82-b967-486a-a9a1-fda6aa4da6a5.png">
目前form提交时，参数值会被截断。因为我们有些接口，参数值这里是需要传入一个很大的json。大概1000个字符。可是目前postcat只能输入大概300个字符。

### Environment

版本0.2.1 (0.2.1)

**Comment by scarqin** [comment]
@fujikang 好的，下个版本修复

**Comment by scarqin** [comment]
@fujikang 已经修复啦
