### ISSUE TITLE
Support for Markdown File

### ISSUE THREAD

**Issue by baymax55** [Postcatlab/postcat#250]
### Describe the feature

just support markdown file

### Environment

just support markdown file

**Comment by scarqin** [comment]
@baymax55 
Export  API in markdown format or write instructions in markdown format
 in the API documentation？

Please rephrase your question and scenes to be used.

**Comment by baymax55** [comment]
I already have a lot of API documents written by markdown, and I want to import them .but it only supports OpenAPI(.json)

**Comment by scarqin** [comment]
@baymax55 Of course, as far as I know markdown does not have a common API format, what is your Markdown API syntax?

**Comment by baymax55** [comment]
> @baymax55 Of course, as far as I know markdown does not have a common API format, what is your Markdown API syntax?
> 
> If it is not a standard format, we have a extensions architecture, and you can upload a import extension： [developer documentation](https://developer.postcat.com/api/feature-contribution/import.html).

thanks for your help, It does not have a public API format for markdown
