### ISSUE TITLE
请求参数示例配置了，但测试时未默认取示例参数

### ISSUE THREAD

**Issue by aoshiguchen** [Postcatlab/postcat#258]
### Describe the bug

请求参数示例配置了，但测试时未默认取示例参数

### Environment

![image](https://user-images.githubusercontent.com/10580997/223678815-81fc74fb-971d-47f1-9418-dc5131f5f531.png)
![image](https://user-images.githubusercontent.com/10580997/223678862-211fe488-79ad-402b-babd-924ee7b0b7aa.png)
![image](https://user-images.githubusercontent.com/10580997/223678899-e9f3ea09-de9f-4bfa-8999-d458dd3074ab.png)

**Comment by scarqin** [comment]
感谢反馈

**Comment by scarqin** [comment]
@aoshiguchen 
昨晚发布的v0.4.0 版本已经修复了这个问题
