### ISSUE TITLE
 I hope to provide a default filter that excludes keys and their corresponding values starting with ":" when importing request headers. 

### ISSUE THREAD

**Issue by VampireAchao** [Postcatlab/postcat#259]
### Describe the feature

<img width="627" alt="1678276058671" src="https://user-images.githubusercontent.com/52746628/223705696-24f7b57c-29e2-41e1-9fde-9020506437c4.png">

 I hope to provide a default filter that excludes keys and their corresponding values starting with ":" when importing request headers. 

### Environment

Postcat V0.3.2

Engine: webkit

EngineVs: 537.36

Supporter: chrome

SupporterVs: 109.0.0.0

System: windows

SystemVs: 10

平台: Web

**Comment by scarqin** [comment]
@VampireAchao Optimized for the next version

**Comment by VampireAchao** [comment]
good job
