### ISSUE TITLE
无法删除参数和返回值

### ISSUE THREAD

**Issue by shui0855** [Postcatlab/postcat#260]
### Describe the bug

编辑了参数或返回值点击保存之后，切换到文档或关闭编辑页，重新打开编辑页删除参数或返回值中的项，点击保存，关闭页面，再重新打开文档页面或者编辑页面，结果之前删掉的项又出现，重复删除再次打开，结果还是无法达到删除效果。
更新到最新的0.3.2结果还是一样，无法删除参数和返回值中的项。

### Environment

版本：0.2.1、0.3.1、0.3.2
系统：win10

**Comment by scarqin** [comment]
@shui0855 麻烦录屏或者描述一下复现步骤。
![20230309173526_rec_](https://user-images.githubusercontent.com/15225835/223981028-820f15c2-8b6b-4a4e-af12-ed9136fb2ce3.gif)

**Comment by shui0855** [comment]
演示的是删除返回值中的字段：
https://user-images.githubusercontent.com/9348021/223986687-3300e99c-169b-46ad-9ee8-263aec336041.mp4

**Comment by scarqin** [comment]
@shui0855 昨晚发布的v0.4.0 版本已经修复了这个问题

**Comment by shui0855** [comment]
@scarqin 大大辛苦了~
问题的确解决了，现在暂没发现其它问题
