### ISSUE TITLE
下载太慢，太慢，太慢

### ISSUE THREAD

**Issue by ji-yc-znr** [Postcatlab/postcat#261]
### Describe the bug

下载太慢，太慢，太慢，提示预计得一天才能下载完成，果断放弃了

### Environment

- 版本: 0.3.2
- Engine: webkit
- EngineVs: 537.36
- Supporter: chrome
- SupporterVs: 107.0.0.0
- System: windows
- SystemVs: 10
- 平台: Web

**Comment by scarqin** [comment]
@ji-yc-znr 如果是 Github 的话可能会慢，官网国内的资源是放在七牛云的，你可以试试。
目前官方的包在三个地方可以下载
1. 官网
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/15225835/224204664-169c877b-3f6c-4ce9-9158-745433cca7de.png">
2. [Github Release](https://github.com/Postcatlab/postcat/releases)
3. [Gitee Release](https://gitee.com/eolink_admin/postcat/releases)
