### ISSUE TITLE
postcat 现在有个功能没有 很不方便 就是全局搜索url路径 我接口很多 我不记得接口名称 只记得接口路径 想全局搜索 没有

### ISSUE THREAD

**Issue by Grayzone007** [Postcatlab/postcat#262]
### Describe the feature

postcat 现在有个功能没有 很不方便 就是全局搜索url路径 我接口很多 我不记得接口名称 只记得接口路径 想全局搜索 没有

### Environment

postcat 现在有个功能没有 很不方便 就是全局搜索url路径 我接口很多 我不记得接口名称 只记得接口路径 想全局搜索 没有

**Comment by yZaio** [comment]
后续我们会在左上角搜索支持这个功能
![image](https://user-images.githubusercontent.com/55974395/224214729-5ecd6c39-cd33-4715-9501-1d29fe5e9f2c.png)

**Comment by scarqin** [comment]
@Grayzone007 或许你希望分组列表显示的是名称还是 URL 呢？

**Comment by scarqin** [comment]
@Grayzone007 Web 已经发布了，支持搜索 URL，下周发布桌面端。
