### ISSUE TITLE
Windows 0.2.x 升级到新版本时不会覆盖旧版本

### ISSUE THREAD

**Issue by suiyueou** [Postcatlab/postcat#266]
### Describe the bug

新版本是重新定义了安装路径吗？

我下载了 `Postcat-Setup-0.3.2.exe` 安装包，从 0.2.0 版本开始升级，但是我发现当我安装完 0.3.2 后，电脑上就会同时存在两个版本。

于是我手动从任务栏固定的老版本进入所在文件夹执行了 `Uninstall Postcat.exe`，然后注册表就被完全无差别清空了。导致新版本文件存在，但是找不到快捷方式图标和控制面板的卸载项。

无奈，只能再次重新执行一遍 `Postcat-Setup-0.3.2.exe`。

新版本不会自动识别已存在的老版本的安装路径和数据吗？

---

ps：这个开机自启的勾选框样式有点分不清，且设置中似乎没有看到这个功能?

![Snipaste_2023-03-12_22-34-09](https://user-images.githubusercontent.com/48700331/224552270-f9fc2a6b-07c7-46f9-8ce4-46d7bde44b7b.png)

pps：这个三方登录的 github 图标不知为何无法加载？我的网络应该是没有问题的。

![image](https://user-images.githubusercontent.com/48700331/224552605-80fe5c86-8f9d-4059-8fe0-6d0ea6ed4fdb.png)

### Environment

- Postcat Version: 0.3.2
- OS: Windows 11

**Comment by scarqin** [comment]
@suiyueou 是 Bug，我们在 3.0 修复了，3.0 之前的包自动升级逻辑有问题。

样式问题我们优化下

**Comment by suiyueou** [comment]
> @suiyueou 是 Bug，我们在 3.0 修复了，3.0 之前的包自动升级逻辑有问题。

听的不是很懂，我是 0.2.0 直升 0.3.2

> 2. https://cdn.eolink.com/10.7.3.4/ng14/assets/images/third_party/github.png 你无法访问这个地址吗？

可能刚刚网路波动了，现在正常了。

**Comment by suiyueou** [comment]
意思是从 0.3.0 版本开始，steup 安装和之前的 0.2.x 将只能是安装成两个完全独立的版本，如果是从老版本升级上来？

意味着之前的 0.2.x 老版本用户在升级至 0.3.x 版本时，都必须提前导出备份 => 完全卸载旧版本 => 安装 0.3.x 新版本？

---

![image](https://user-images.githubusercontent.com/48700331/224555438-347719e3-455f-4a81-b625-04de8a63d5c6.png)

这个地方的路径除了显示安装路径，是否可以将数据存储和缓存路径一起标示出？

**Comment by scarqin** [comment]
@suiyueou 不是独立的版本，之前 0.2.x 系列的包自动升级有问题，自动升级时没有覆盖原目录，升级后安装到了默认目录，所以 Windows 下会有两个程序。

从 0.2.x 升级到 0.3.x 不需要提前备份，我们数据地址和安装地址是分开的，仅需要重新安装 0.3.2。

标记缓存地址没问题，感谢你的建议

**Comment by suiyueou** [comment]
> @suiyueou 不是独立的版本，之前 0.2.x 系列的包自动升级有问题，自动升级时没有覆盖原目录，升级后安装到了默认目录，所以 Windows 下会有两个程序。

哦哦哦，大概听明白了，就是 0.2.x 版本的时候，用 setup 安装的安装路径没有规范，0.3.x 开始规范了

> 从 0.2.x 升级到 0.3.x 不需要提前备份，我们数据地址和安装地址是分开的，仅需要重新安装 0.3.2。

咦，那不对呀，执行卸载程序不会连同数据文件夹一起清空的嘛，如果先安装 0.3.x 然后卸载掉 0.2.x 旧版本的时候

突然反应过来，这里我昨天升级完后，执行 uninstall 卸载 0.2.x 旧版本的步骤可能走错了，我这里直接删除旧版本安装文件夹就行了（捂脸

**Comment by scarqin** [comment]
@suiyueou 哈哈你的描述比我清晰且反应很快，终究是这个 bug 影响了操作，抱歉抱歉。

兼容在我们发 0.3.x 的时候就不太好做了（因为 0.2.x 的用户大部分已经自动升级了）。

**Comment by suiyueou** [comment]
> @suiyueou 哈哈你的描述比我清晰且反应很快，终究是这个 bug 影响了操作，抱歉抱歉。
> 
> 兼容在我们发 0.3.x 的时候就不太好做了（因为 0.2.x 的用户大部分已经自动升级了）。
> 

好的，明白啦（✓
