### ISSUE TITLE
插件点击安装没有反应

### ISSUE THREAD

**Issue by Gszekt** [Postcatlab/postcat#268]
### Describe the bug

客户端下载插件时点击安装没有响应，网页版没有问题

### Environment

客户端版本：V0.3.2

![Dingtalk_20230314134617](https://user-images.githubusercontent.com/26792853/224907692-31c709ec-2040-4352-9a14-07141a7cf1ca.jpg)

**Comment by scarqin** [comment]
@Gszekt 麻烦在**插件安装目录**下打开 cmd，然后将 exe 执行文件拖入到 cmd 窗口中，enter 运行。
再次点击安装截图下报错。


ps：0.3.2 版本修复了这个问题，如果没有安装 Node 环境插件就会失败。
![image](https://user-images.githubusercontent.com/15225835/224907860-921187df-17ee-4fa7-8bc7-3a782272c20c.png)

**Comment by Gszekt** [comment]
![图片](https://user-images.githubusercontent.com/26792853/224912042-4749d2fb-b2a4-4451-b9ed-cade5cf56ee8.png)
我本机有 node，@scarqin

**Comment by scarqin** [comment]
https://github.com/npm/npm/issues/10826
@Gszekt 麻烦运行一下 npm  run cache 试试
![image](https://user-images.githubusercontent.com/15225835/224934141-118e8d58-bc82-4604-a78f-89945b479bd0.png)

**Comment by Gszekt** [comment]
@scarqin 我是全新安装的，之前没有安装过

**Comment by scarqin** [comment]
@Gszekt 运行了 npm run cache 后怎么样？

**Comment by Gszekt** [comment]
@scarqin 这个命令不对，是 npm cache clean 吧？试了不太行

**Comment by scarqin** [comment]
![image](https://user-images.githubusercontent.com/15225835/224974844-0053980b-4b46-40e9-8d97-e73346027d19.png)
麻烦加一下反馈群我们远程看看

**Comment by Pan-Zi** [comment]
![image](https://user-images.githubusercontent.com/68836675/229078907-acb34441-07b3-4d71-9716-72e28849fc1b.png)

**Comment by scarqin** [comment]
@Pan-Zi 试试用管理员权限运行再安装
