### ISSUE TITLE
没有找到linux客户端的下载地址

### ISSUE THREAD

**Issue by NS-FDF** [Postcatlab/postcat#271]
### Describe the bug

官网上没找到linux版本的客户端
![image](https://user-images.githubusercontent.com/49178586/225200467-49a97f13-20f7-4c4b-9e18-586468a9bf0d.png)

### Environment

os:linux ubuntu

**Comment by scarqin** [comment]
@NS-FDF Liniux 客户端我们打包了，但是没有进行详细的测试，所以没有完全开放，如果需要可以访问：https://github.com/Postcatlab/postcat/releases
下载

**Comment by NS-FDF** [comment]
> @NS-FDF Liniux 客户端我们打包了，但是没有进行详细的测试，所以没有完全开放，如果需要可以访问：https://github.com/Postcatlab/postcat/releases 下载

好的，感谢
