### ISSUE TITLE
插件市场暂无数据是咋回事

### ISSUE THREAD

**Issue by hzh-test** [Postcatlab/postcat#275]
### Describe the feature

插件市场暂无数据是咋回事

### Environment

- 版本: 0.4.0
- Engine: webkit
- EngineVs: 537.36
- Supporter: chrome
- SupporterVs: 105.0.0.0
- System: windows
- SystemVs: 10
- 平台: Web

**Comment by scarqin** [comment]
@hzh-test 可能是网络波动，尝试切换个网络或者刷新试试。

如果还是不行，控制台打开一下截图看看请求返回
