### ISSUE TITLE
升级4.0后没有发送请求按钮

### ISSUE THREAD

**Issue by zerofancy** [Postcatlab/postcat#278]
### Describe the bug

今天尝试测试一个jwt认证的接口，认证不成功，然后发现token无法完整粘贴到Header中，看起来限制了输入长度。

token示例：

eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6Imt0b3IuaW8iLCJpZCI6MSwiY291bnRyaWVzIjpbIkVneXB0IiwiQXVzdHJpYSJdLCJleHAiOjE2NzkyNTIyMjJ9.aXqyk_sv-eX1PVVQLOc3Z-N5NN7jyDeWC81mTKHGiZyyZKLBc1YYD_4fC3r61Ur8Rmng7BT3-kTBzKj-qxFbaQ

粘贴结果：

Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6Imt0b3IuaW8iLCJpZCI6MSwiY291bnRyaWVzIjpbIkVneXB0IiwiQXVzdHJpYSJdLCJleHAiOjE2NzkyNTIyMjJ9.aXqyk_sv-eX1PVVQLOc3Z-N5NN7jyDeWC81mTKHGiZyyZKLBc1YYD_4fC3r61Ur8Rmng7BT3-kTBz

### Environment

- PostCat Version: V0.2.1
- OS: KUbuntu 22.04 LTS

**Comment by scarqin** [comment]
@zerofancy 请升级一下客户端，目前最新的已经是 0.4.0 了

**Comment by zerofancy** [comment]
> @zerofancy 请升级一下客户端，目前最新的已经是 0.4.0 了，此问题已在 0.3.1 修复。 ![image](https://user-images.githubusercontent.com/15225835/226165233-460f7e27-82bf-4174-8408-bbbef0a82bd4.png)

升级0.4.0后无测试按钮

![图片](https://user-images.githubusercontent.com/40628516/226165614-52df1959-258b-417e-b982-88e2ec9496e1.png)

**Comment by zerofancy** [comment]
我的问题已经解决，感谢你的帮助！

**Comment by scarqin** [comment]
@zerofancy 好的，但是默认高度这么高我觉得也不太合理，你是自己拖动的还是更新后就这样？
