### ISSUE TITLE
windows 客户端安装闪退

### ISSUE THREAD

**Issue by yimiaoxiehou** [Postcatlab/postcat#288]
### Describe the bug

windows 客户端安装闪退，点击快速安装 / 自定义安装 后安装进度条显示（进度0）后立即闪退

### Environment

i5-10400 + 32 GB + hp办公机

| | |
| -- | -- |
| 版本 | Windows10专业版 |
| 版本号 | 22H2 |
| 安装日期 | 2021/3/5 |
| 操作系统内部版本 | 19045.2364 |
| 体验 | Windows Feature Experience Pack 120.2212.4190.0 |

**Comment by scarqin** [comment]
@yimiaoxiehou 
1. 请问有安装什么杀毒软件吗?
2. 试试用管理员权限打开安装包安装能否打开
3. 如果还是不行，方便向日葵远程看看吗，可以加我 QQ:1054139596

**Comment by yimiaoxiehou** [comment]
@scarqin 
1. 有火绒和公司的一个杀毒软件，但是这两个都没对应的拦截记录
2. 安装包一直能打开，问题是安装闪退（管理员权限也一样）
3.  qq联系吧

**Comment by scarqin** [comment]
初步定位：安装包 nsis7z.dll 插件问题
