### ISSUE TITLE
win11系统无法安装

### ISSUE THREAD

**Issue by zengxiong1995** [Postcatlab/postcat#290]
### Describe the bug

作者你好，我安装了几次，都是没有反应的。尝试使用过管理员运行还是一样的，点击安装没有反应，过一会后自动退出。exe版本莫名无法安装和没有反应

### Environment

postcat version:  0.4.2
install package:  [Postcat-Setup-0.4.2.exe](https://github.com/Postcatlab/postcat/releases/download/v0.4.2/Postcat-Setup-0.4.2.exe)

**Comment by scarqin** [comment]
duplicate: https://github.com/Postcatlab/postcat/issues/290

**Comment by scarqin** [comment]
@jasonliao909 遇到了这个问题吗？

**Comment by jasonliao909** [comment]
@scarqin 0.4.x遇到这个问题，今天上午下的Postcat-Setup-0.5.0.exe是72M的，刚下的是86M的，两个都试了没有问题。

**Comment by scarqin** [comment]
@jasonliao909 那就好～～用下午的，早上的自动升级会失败
