### ISSUE TITLE
环境变量中的参数怎么无法使用

### ISSUE THREAD

**Issue by shui0855** [Postcatlab/postcat#293]
### Describe the bug

在环境变量中设置好了参数，然后使用结果，发生异常：
1、在url中使用，如:"/api/act/get/{{id}}"，结果返回"HTTP Status 400 – Bad Request"，而将{{id}}替换成正常的整数值则结果正常；
2、在http请求头部使用，如:Authorization的值为{{jwt_token}}，作用是权限验证，结果为"认证失败"，而将{{jwt_token}}换成token的字符串值，结果又是正确的。
这个问题在以前的版本中没发现，之前的api测试时还是是正常的，现在出现问题了。
环境变量在其它的地方的使用，暂未用到，所以还未测试到。

### Environment

Postcat-0.5.0.exe 和 Postcat-0.4.2.exe
win10 x64

**Comment by scarqin** [comment]
![image](https://user-images.githubusercontent.com/15225835/230260547-d650b0cb-11c2-4994-bd84-98bb7f086d29.png)
@shui0855 复现了，我们这周发布一个修复版本

**Comment by scarqin** [comment]
@shui0855 已经发布啦
