### ISSUE TITLE
安装依赖的时候有报错，yarn build运行报错

### ISSUE THREAD

**Issue by 13076989842** [Postcatlab/postcat#302]
### Describe the bug

yarn install安装依赖的时候有报错
![1](https://user-images.githubusercontent.com/21237537/233550328-1f38117d-6ce2-4091-accf-0d60c1430657.png)

yarn build报错如下
![2](https://user-images.githubusercontent.com/21237537/233550395-1f03df16-59e8-4baa-b82a-273708cedd82.png)

yarn build:win:noSign报错如下
![3](https://user-images.githubusercontent.com/21237537/233550588-85f1ba16-7bc9-4fcd-a6a7-da8bba13e08c.png)

@

### Environment

win10
node 16.18.0

**Comment by scarqin** [comment]
好的我试试 windows

**Comment by scarqin** [comment]
https://github.com/Postcatlab/postcat/pull/336
