### ISSUE TITLE
postman导入插件安装不成功

### ISSUE THREAD

**Issue by l90z11** [Postcatlab/postcat#305]
### Describe the feature

postman导入插件安装不了，一直在loading

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.19044
- 平台: Electron

**Comment by scarqin** [comment]
@l90z11 麻烦执行以下操作：在安装目录下运行 exe

**Comment by zhangbo-chn** [comment]
![image](https://user-images.githubusercontent.com/10509611/236362724-53413a4d-7842-46cf-8b8b-e012cd61666a.png)
相同错误，导入Postman 插件安装一直loading

**Comment by scarqin** [comment]
@zhangbo-chn  麻烦执行以下操作：
在安装目录下运行 exe
应用运行，点击安装 Postcat
截图一下此刻 exe 的输出的错误信息

**Comment by zhangbo-chn** [comment]
> 

没太懂哪里有输出错误的。在安装目录点击“Postcat.exe”运行程序，然后安装其他插件都是可以的，没有报错。只有安装“导入Postman”插件时一直不成功，也没有报错信息

**Comment by zhangbo-chn** [comment]
> @zhangbo-chn 麻烦执行以下操作： 在安装目录下运行 exe 应用运行，点击安装 Postcat 截图一下此刻 exe 的输出的错误信息

没太懂哪里有输出错误的。在安装目录点击“Postcat.exe”运行程序，然后安装其他插件都是可以的，没有报错。只有安装“导入Postman”插件时一直不成功，也没有报错信息

**Comment by scarqin** [comment]
@zhangbo-chn @l90z11 试了下，应该是中文版本桌面端可以复现，因为中文版本走的是国内的 cnpm 资源，cnpm 上没有更新 import-postman 的包，目前应该可以了，你们试试
