### ISSUE TITLE
chat GPT  plugin 

### ISSUE THREAD

**Issue by pengbinbin1** [Postcatlab/postcat#311]
### Describe the feature

现在使用chatGPT必须要提供OPENAPI_KEY 了吗？之前是可以直接用的？

### Environment

网页版

**Comment by Jack-123-power** [comment]
Hello，由于 Postcat 用户数量太大，出于对调用成本以及性能瓶颈的考虑，我们不再免费提供此服务，后续改为用户通过输入自己的 OpenAPI 的 key 可继续使用，或者去搜索同类型可提供此服务的工具，谢谢理解与支持！

**Comment by pengbinbin1** [comment]
每次对话都要输入openAPI的key？
![image](https://github.com/Postcatlab/postcat/assets/28950491/99051b96-4d44-4b2e-9c00-050e2f513ef3)
