### ISSUE TITLE
 Couldn't find the extension 

### ISSUE THREAD

**Issue by ky0911** [Postcatlab/postcat#318]
### Describe the bug

I can't find the extension. When I  click on the Extensions, it shows 'No Data'.

### Environment

- 版本: v0.5.1
- 引擎: Webkit
- 引擎版本: unknow
- 平台: Chrome
- 浏览器版本: 114.0.0.0
- 操作系统: Windows
- 系统版本: unknow
- 平台: Web

**Comment by scarqin** [comment]
@ky0911 has been fixed,thanks for the feedback.
