### ISSUE TITLE
New Extension Request:希望可以支持导入curl

### ISSUE THREAD

**Issue by ealung** [Postcatlab/postcat#324]
### Describe the feature

新增请求可以像postman一样支持粘贴curl进行导入

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin x64 22.4.0
- 平台: Electron

**Comment by scarqin** [comment]
https://github.com/Postcatlab/postcat/issues/244

**Comment by scarqin** [comment]
已经支持啦
