### ISSUE TITLE
yarn build  执行 build-for-electron-postcat.bat 卡死在这里了

### ISSUE THREAD

**Issue by asdwsxzc123** [Postcatlab/postcat#332]
### Describe the bug

![image](https://github.com/Postcatlab/postcat/assets/30801141/05b4e573-d816-4d52-a209-5ea9ca8fb626)

electron-builder 打包好了Postcat Setup 0.5.2.exe,卡死在 cd build && build-for-electron-postcat.bat
是不是有部分代码没有

![image](https://github.com/Postcatlab/postcat/assets/30801141/d9a780f5-3ace-4e97-861b-82543761c4ad)

### Environment

- OS: windows 10.0.19045 内部版本 19045
- node: v14.17.2
- yarn: v1.22.19

**Comment by scarqin** [comment]
是的，用 build:nosign

签名文件走不了
