### ISSUE TITLE
是否支持私有化部署？

### ISSUE THREAD

**Issue by simazilin** [Postcatlab/postcat#341]
### Describe the feature

我们公司是内网协同开发的，请问有私有化部署的版本么?
没有的话，未来是否有这个计划？

### Environment

v0.5.1

**Comment by scarqin** [comment]
暂时没有开源的计划，之前尝试过开源服务端，但部署和维护的成本太高了。还是希望将精力投入到插件架构上，里面有详细介绍原因：https://github.com/Postcatlab/postcat/issues/215

**Comment by chenyulun** [comment]
必源产品页能打开源旗号的吗？
