### ISSUE TITLE
开发导出插件时本地logo能在插件广场显示,导出时显示不了

### ISSUE THREAD

**Issue by heguangyu5** [Postcatlab/postcat#350]
### Describe the bug

package.json 里 logo 都用了本地图片文件 ./logo.png

```
{
  "name": "postcat-export-as-w4af-requests-b64",
  "version": "0.0.1",
  "description": "The export extension of postcat",
  "title": "Export as w4af requests.b64",
  "main": "dist/index.js",
  "logo": "./logo.png",
  "scripts": {
    "build": "rollup -c rollup.config.js",
    "build:watch": "rollup -w -c rollup.config.js"
  },
  "devDependencies": { "rollup": "^2.70.2" },
  "features": {
    "exportAPI": {
      "action": "exportFunc",
      "label": "w4af(requests.b64)",
      "description": "",
      "icon": "./logo.png",
      "filename": "requests.b64"
    }
  }
}
```

**插件广场显示正常**

![Screenshot from 2023-09-19 10-39-24](https://github.com/Postcatlab/postcat/assets/468242/62968a4a-b765-4476-a424-ebe3a4fa68e5)

**导出时显示不了**

![Screenshot from 2023-09-19 10-41-19](https://github.com/Postcatlab/postcat/assets/468242/3e9b1762-59fe-4934-bce9-6e12f48969ff)

### Environment

Postcat-0.5.2.AppImage

**Comment by scarqin** [comment]
暂时不支持本地图片，请用在线图片～～
