### ISSUE TITLE
Windows 11， 插件广场为空。

### ISSUE THREAD

**Issue by likaboy** [Postcatlab/postcat#353]
### Describe the bug

开放家庭网络和专用网络，并尝试重启软件，插件列表依然任何插件，
浏览器打开-进入插件广场-显示倒是正常。

另：点击导入，跳转到插件广场，依然没有任何插件。

版本	Windows 11 专业版
版本	22H2
安装日期	‎2023/‎7/‎18
操作系统版本	22621.2283
体验	Windows Feature Experience Pack 1000.22662.1000.0

有使用clash, 且clash 正常运行。

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621
- 平台: Electron

**Comment by scarqin** [comment]
electron 打开一下控制台看看接口返回

**Comment by likaboy** [comment]
> electron 打开一下控制台看看接口返回

`GET https://extensions.postcat.com/list?locale=zh-Hans&category=Data%20Migration&keyword= net::ERR_CONNECTION_RESET`，

这个地址Firefox 直连失败，需要代理才会下发数据。

**Comment by likaboy** [comment]
看了下，新加坡的ip，大陆个别地区访问不了，我自己上代理吧。
