### ISSUE TITLE
New Extension Request: import from curl format

### ISSUE THREAD

**Issue by tty86400** [Postcatlab/postcat#354]
### Describe the feature

strongly need this feature!!!

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621
- 平台: Electron

**Comment by tty86400** [comment]
#244 already support, sorry

**Comment by scarqin** [comment]
Thanks for the feedback, we will try to extensible in the future.
