### ISSUE TITLE
这个项目服务器会开源吗

### ISSUE THREAD

**Issue by huluohu** [Postcatlab/postcat#364]
### Describe the feature

你好，请问这个项目的服务器端开源吗，比如使用postcat登录到自部署的服务器端。

### Environment

- Postcat Version V0.5.1

**Comment by scarqin** [comment]
暂时没有开源的计划，之前尝试过开源，但部署和维护的成本太高了。还是希望将精力投入到插件架构上，里面有详细介绍原因：https://github.com/Postcatlab/postcat/issues/215

**Comment by huluohu** [comment]
> 暂时没有开源的计划，之前尝试过开源服务端，但部署和维护的成本太高了。还是希望将精力投入到插件架构上，里面有详细介绍原因：#215

好的了解啦，之前自部署的我也使用过，感谢哈。
