### ISSUE TITLE
Is there no ability to batch execute apis?

### ISSUE THREAD

**Issue by sunny-xiabo** [Postcatlab/postcat#366]
### Describe the bug

Is there no ability to batch execute apis?

### Environment

- 版本: 0.5.2
- 引擎: Webkit
- 引擎版本: unknow
- 平台: Chrome
- 浏览器版本: 118.0.0.0
- 操作系统: Macos
- 系统版本: unknow
- 平台: Web

**Comment by scarqin** [comment]
There is a plan to implement it, and the approximate effect may be like this：
<img width="354" alt="image" src="https://github.com/Postcatlab/postcat/assets/15225835/fdcc1a3c-b2c3-4ebf-84d1-d97658af5f0a">

**Comment by sunny-xiabo** [comment]
okay, hope to get it online soon.
