### ISSUE TITLE
能不能加一个支持insomnia的格式文件

### ISSUE THREAD

**Issue by bing086** [Postcatlab/postcat#377]
### Describe the feature

能不能加一个支持insomnia导出的文件

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin x64 21.5.0
- 平台: Electron

**Comment by scarqin** [comment]
可以考虑自己开发：https://developer.postcat.com/api/feature-contribution/export.html
