### ISSUE TITLE
在macos上图标有点大

### ISSUE THREAD

**Issue by onechives** [Postcatlab/postcat#392]
### Describe the feature

[icon.zip](https://github.com/Postcatlab/postcat/files/13792549/icon.zip)
我用Image2Icon把尺寸修改了一下 以适应Big Sur以后的macOS图标尺寸规范

### Environment

Electron: 22.1.0

Chromium: 108.0.5359.179

Node.js: 16.17.1

V8: 10.8.168.25-electron.0

OS: Darwin x64 22.6.0

Install Location: /Applications/Postcat.app/Contents/MacOS

平台: Electron

**Comment by scarqin** [comment]
@onechives 感谢～

你方便提交一个 PR 吗，可以作为贡献者我合并。不方便的话我晚点改一下
