### ISSUE TITLE
mac intel客户端没办法登录

### ISSUE THREAD

**Issue by big-cat-666** [Postcatlab/postcat#396]
### Describe the bug

网页端可以登录，下载的mac intel客户端没办法登录

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin x64 23.2.0
- 平台: Electron

**Comment by scarqin** [comment]
F12 看一下接口情况

**Comment by big-cat-666** [comment]
> F12 看一下接口情况

安装的客户端怎么看接口情况呀，网页端可以正常登录

**Comment by jimwong666** [comment]
> > F12 看一下接口情况
> 
> 安装的客户端怎么看接口情况呀，网页端可以正常登录

window 平台时 ctrl + shift + i，mac 可以对应试一下

**Comment by scarqin** [comment]
这个问题没有后续，大概率和网络相关，先关闭
