### ISSUE TITLE
New Extension Request可以支持curl导入请求吗

### ISSUE THREAD

**Issue by fwj-21890910** [Postcatlab/postcat#398]
### Describe the feature

 Request可以支持curl导入请求吗

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin arm64 23.1.0
- 平台: Electron

**Comment by scarqin** [comment]
地址栏粘贴 curl 就可以啦

**Comment by scarqin** [comment]
https://github.com/Postcatlab/postcat/issues/354
