### ISSUE TITLE
导出 OpenAPI 插件安装 一直 loading

### ISSUE THREAD

**Issue by sa0ChunLuyu** [Postcatlab/postcat#399]
### Describe the bug

换了 三种 网络环境，  切换了 语言  。仍然没有解决。
![Snipaste_2024-01-21_18-03-56](https://github.com/Postcatlab/postcat/assets/46621242/fdb90a5c-3913-4b01-b5b9-2ec693620616)
![Snipaste_2024-01-21_18-05-47](https://github.com/Postcatlab/postcat/assets/46621242/55065ea8-59d1-4a06-a4cd-d2a0d447301a)

### Environment

Electron: 22.1.0

Chromium: 108.0.5359.179

Node.js: 16.17.1

V8: 10.8.168.25-electron.0

OS: Darwin arm64 23.1.0

Install Location: /Applications/Postcat.app/Contents/MacOS

平台: Electron

**Comment by scarqin** [comment]
@sa0ChunLuyu 我们是从 npm 下载资源的，目前可以了吗？
还是不行的话，可以尝试离线。
https://docs.postcat.com/docs/local-install-extension.html
