### ISSUE TITLE
建议提供脚本操作的详细文档

### ISSUE THREAD

**Issue by trifolium-wang** [Postcatlab/postcat#402]
### Describe the feature

建议提供脚本操作的详细文档，我在编写前置后置脚本时发现无法引入第三方组件，希望能有一份复杂脚本的样例，或者npm本地导入全局第三方库使用。

### Environment

MacOS 14,  postcat: 0.5.1

**Comment by scarqin** [comment]
@trifolium-wang 了解，目前脚本使用的是和 Postman 一样的语法，减少大家上手成本，后续会推出文档

**Comment by trifolium-wang** [comment]
感谢作者为开源事业做出的贡献。
