### ISSUE TITLE
idea最新版本不支持了

### ISSUE THREAD

**Issue by lizhuangs** [Postcatlab/postcat#403]
### Describe the feature

idea最新版本不支持了，仓库也搜索不到了。好久没更新了。

### Environment

最新版本

**Comment by Changeeer** [comment]
您好，我们已经收到反馈，我们争取在节前更新插件。

**Comment by Changeeer** [comment]
您好，新版本1.3.2的插件已支持最新版本idea，请更新使用。链接：https://plugins.jetbrains.com/plugin/21182-postcat/versions/stable/482138
