### ISSUE TITLE
New Extension Request:支持根据curl创建请求

### ISSUE THREAD

**Issue by sry1201** [Postcatlab/postcat#404]
### Describe the feature

支持根据curl创建请求

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Windows_NT x64 10.0.22621
- 平台: Electron
/

**Comment by scarqin** [comment]
https://github.com/Postcatlab/postcat/issues/398
@tetris-account @sry1201 可能该功能比较隐蔽，本身已经支持啦
