### ISSUE TITLE
New Extension Request:cURL import data

### ISSUE THREAD

**Issue by Ling137** [Postcatlab/postcat#423]
### Describe the feature

cURL import data

### Environment

- 版本: 0.5.1
- Electron: 22.1.0
- Chromium: 108.0.5359.179
- Node.js: 16.17.1
- V8: 10.8.168.25-electron.0
- OS: Darwin arm64 21.6.0
- 平台: Electron

**Comment by scarqin** [comment]
https://github.com/Postcatlab/postcat/issues/404
