### ISSUE TITLE
如何在脚本中实现把login后的token保存到全局变量中

### ISSUE THREAD

**Issue by MooreManor** [Postcatlab/postcat#428]
### Describe the feature

pc.response这样好像获取不到返回体，postcat中如何获得返回体呢

### Environment

Postcat V0.4.0

**Comment by joelcho** [comment]
我是这么做的

```javascript
const response = JSON.parse(pc.http.responseParam)
pc.globals.set("admin_login_session_id", response.data.myToken);
```

你可以用 eo.info() 输出一下 pc 里面的内容

**Comment by MooreManor** [comment]
好的谢谢，主要是没看到文档里写脚本这些API如何用，希望以后文档里能提供
