### ISSUE TITLE
启动服务报错

### ISSUE THREAD

**Issue by lewis-ing** [Postcatlab/postcat#437]
### Describe the bug

基本信息：
npm -version： 10.7.0
yarn -v： 4.5.0

使用yarn install 安装正常

yarn start或yarn start:web 启动错误信息：
![image](https://github.com/user-attachments/assets/dbc0adae-7801-4cc7-adb8-fd21e40c205f)

### Environment

windows11环境

**Comment by scarqin** [comment]
@lewis-ing 看起来是依赖没有安装好，packakge.json eo-ng-tree 的版本是多少

**Comment by lewis-ing** [comment]
@scarqin 1、从https://github.com/Postcatlab/postcat中的main分支拉取的，不可以；
2、开始升级对eo-ng-tree升级(还是不可以)，如下图：
![image](https://github.com/user-attachments/assets/df2d1b81-419e-458a-95de-05d2199a4a34)

**Comment by scarqin** [comment]
可以根据报错检查下安装的包是不是缺失内容了
